export const iconsMap = [
  { className: 'icon-account-circle', description: 'account circle' },
  { className: 'icon-add', description: 'add' },
  { className: 'icon-add-call', description: 'add call' },
  { className: 'icon-add-chart', description: 'add chart' },
  { className: 'icon-add-circle-outline', description: 'add circle outline' },
  { className: 'icon-alternate-email', description: 'alternate email' },
  { className: 'icon-arrow-down-circle', description: 'arrow down circle' },
  { className: 'icon-arrow-downward', description: 'arrow downward' },
  { className: 'icon-arrow-up-circle', description: 'arrow up circle' },
  { className: 'icon-arrow-upward', description: 'arrow upward' },
  { className: 'icon-assignment', description: 'assignment' },
  { className: 'icon-assignment-late', description: 'assignment late' },
  { className: 'icon-auto-renew', description: 'auto renew' },
  { className: 'icon-avatar-plcaholder', description: 'avatar placeholder' },
  { className: 'icon-bolt-circle', description: 'bolt circle' },
  { className: 'icon-bookmark-border', description: 'bookmark border' },
  { className: 'icon-check-circle', description: 'check circle' },
  { className: 'icon-check-circle-solid', description: 'check circle solid' },
  { className: 'icon-clipboard', description: 'clipboard' },
  { className: 'icon-close', description: 'close' },
  { className: 'icon-close-circle', description: 'close circle' },
  { className: 'icon-close-solid', description: 'close solid' },
  { className: 'icon-collapse', description: 'collapse' },
  { className: 'icon-comment', description: 'comment' },
  { className: 'icon-delete', description: 'delete' },
  { className: 'icon-detect', description: 'detect' },
  { className: 'icon-download', description: 'download' },
  { className: 'icon-drop-down-arrow', description: 'drop down arrow' },
  {
    className: 'icon-drop-down-arrow-collapse',
    description: 'drop down arrow collapse',
  },
  { className: 'icon-edit', description: 'edit' },
  { className: 'icon-edit-square', description: 'edit square' },
  { className: 'icon-email', description: 'email' },
  { className: 'icon-emergency', description: 'emergency' },
  { className: 'icon-entity', description: 'entity' },
  { className: 'icon-expand', description: 'expand' },
  { className: 'icon-extract', description: 'extract' },
  { className: 'icon-favorite-border', description: 'favorite border' },
  { className: 'icon-fuul-screen', description: 'full screen' },
  { className: 'icon-grid-view', description: 'grid view' },
  { className: 'icon-group', description: 'group' },
  { className: 'icon-history', description: 'history' },
  { className: 'icon-home', description: 'home' },
  { className: 'icon-image-solid', description: 'image solid' },
  { className: 'icon-info', description: 'info' },
  { className: 'icon-inside-organization', description: 'inside organization' },
  { className: 'icon-intent', description: 'intent' },
  { className: 'icon-keyboard', description: 'keyboard' },
  { className: 'icon-link', description: 'link' },
  { className: 'icon-lock', description: 'lock' },
  { className: 'icon-login', description: 'login' },
  { className: 'icon-message', description: 'message' },
  { className: 'icon-money-circle', description: 'money circle' },
  { className: 'icon-more-horizontal', description: 'more horizontal' },
  { className: 'icon-more-vert', description: 'more vert' },
  { className: 'icon-movie', description: 'movie' },
  { className: 'icon-navigate-before', description: 'navigate before' },
  { className: 'icon-navigate-next', description: 'navigate next' },
  { className: 'icon-notification', description: 'notification' },
  { className: 'icon-notification-on', description: 'notification on' },
  {
    className: 'icon-outside-organization',
    description: 'outside organization',
  },
  { className: 'icon-perm-media', description: 'perm media' },
  { className: 'icon-person-pin', description: 'person pin' },
  { className: 'icon-phrase', description: 'phrase' },
  { className: 'icon-preview', description: 'preview' },
  { className: 'icon-publish', description: 'publish' },
  { className: 'icon-push-pin', description: 'push pin' },
  { className: 'icon-remove', description: 'remove' },
  {
    className: 'icon-remove-circle-outline',
    description: 'remove circle outline',
  },
  { className: 'icon-rename', description: 'rename' },
  { className: 'icon-report-problem', description: 'report problem' },
  { className: 'icon-save', description: 'save' },
  { className: 'icon-save-alt', description: 'save alt' },
  { className: 'icon-search', description: 'search' },
  {
    className: 'icon-sentiment-dissatisfied',
    description: 'sentiment dissatisfied',
  },
  {
    className: 'icon-sentiment-extremely-dissatisfied',
    description: 'sentiment extremely dissatisfied',
  },
  { className: 'icon-sentiment-neutral', description: 'sentiment neutral' },
  { className: 'icon-sentiment-satisfied', description: 'sentiment satisfied' },
  {
    className: 'icon-sentiment-very-satisfied',
    description: 'sentiment very satisfied',
  },
  { className: 'icon-settings', description: 'settings' },
  { className: 'icon-settings-filled', description: 'settings filled' },
  { className: 'icon-share', description: 'share' },
  { className: 'icon-shared-slide-solid', description: 'shared slide solid' },
  { className: 'icon-star', description: 'star' },
  { className: 'icon-star-border', description: 'star border' },
  { className: 'icon-star-half', description: 'star half' },
  { className: 'icon-syncing-circle', description: 'syncing circle' },
  { className: 'icon-team', description: 'team' },
  { className: 'icon-user', description: 'user' },
  { className: 'icon-video', description: 'video' },
  { className: 'icon-video-library', description: 'video library' },
  { className: 'icon-visibility', description: 'visibility' },
  { className: 'icon-visibility-off', description: 'visibility off' },
  { className: 'icon-zap', description: 'zap' },
  { className: 'icon-zoom-in', description: 'zoom in' },
  { className: 'icon-zoom-out', description: 'zoom out' },
];
