name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or the branch you want to trigger the deployment on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # or the version you prefer

      - name: Build and deploy
        run: |
          npm install  # or `npm install` if you have a package-lock.json file
          npm run build-storybook  # adjust the build command to your project

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # or the branch you want to deploy to
          publish_dir: ./build  # adjust the directory where your built files are located