name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or the branch you want to trigger the deployment on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # or the version you prefer

      - name: Install and Build
        run: |
            pwd
            npm install
            npm run build-storybook -- -o storybook-static
            ls -la

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static